### ISSUE TITLE
Fixed asset Job work order

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#119]
While creating Fixed asset Job work order items not creating in Delivery challan page we need to send each item by item so we need to sort this issue

**Comment by ramapandian14** [comment]
1.Fixed asset Job work order items creating in Delivery challan page.
2.**We need to send each item by item**
It is not a issue.
Its Navision standard functionality.
It will applicable (If you are having 10 lines in Job Work.User will click 10 times to send and receive also because technically its a correct method to do activity from end user)
If user is Sending a item as Item A
and receiving a item as Item B
User will click ->Job Work order dispatch ->Send->Enter Delivery challan Date
Click ->Send to send a material to vendor location..

**Comment by YashwanthGowdaJ** [comment]
As per discussion with @IT-Saravanan ,

As per his logic : While clicking send button in subcontracting order, it opens subcontracting delivery lines page, which is actually a purchase line table. According to him, users needs to select multiple lines, all these lines should populate in single Subcontracting delivery lines, which is not possible. Because subcontracting delivery lines is from purchase line. Each purchase line can contain only 1 record. We cannot merge with multiple lines.

As discussed with him, this logic is not appropriate
