### ISSUE TITLE
Report Salary Details Summary

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#20]
Report ID: 33010144

**Comment by YashwanthGowdaJ** [comment]
The following changes were made as per Subash Sir,

Report request page is changed as per the request. Previously report can run only for 1 month at a time. Now based on From and To fields in request page, user can run for multiple months for the selected payroll.
Bonus amount is corrected.
Included new column by name CTCPayout .
Salary/Wages column is removed.
Pertol conveyance, Ayudha Pooja & other fields were updated with recent values.
Travel conveyance by company vehicle column is included for those employees whose in payelements Travel Conveyance pay element is not available.
For 2016-17 ( April, May & June) we have developed a new report(33010236) because those data is not available in 2016. So we have created new tables(Processed salary, Monthly attendance, Bonus Header & Bonus Line) imported data from 2009 database.
As data is not proper for 2017-18 year, we have hardcoded bonus year as 2016-2016 & 2017-2017.

**Comment by YashwanthGowdaJ** [comment]
[Rep salary details summary 33010144 as on 290220.txt](https://github.com/BPS-Industries/Navision/files/4269993/Rep.salary.details.summary.33010144.as.on.290220.txt)

**Comment by YashwanthGowdaJ** [comment]
New column is included for stipend amount. This column will be applicable only in the case where employee category is Trainee, whose pay elements contains 'STIPEND'
[Rep  salary details  summary 33010144 as on 290220.txt](https://github.com/BPS-Industries/Navision/files/4270049/Rep.salary.details.summary.33010144.as.on.290220.txt)

**Comment by YashwanthGowdaJ** [comment]
Previously, for professional qualification, actual amount was taken. I have corrected to payable amount. Same thing is included in Gross Pay & earned gross columns as per Subash.
[Rep 33010144 Salary details summary as on 050320.txt](https://github.com/BPS-Industries/Navision/files/4291644/Rep.33010144.Salary.details.summary.as.on.050320.txt)
