### ISSUE TITLE
Report Employee Gross Details

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#21]
Report id : 33010308

**Comment by prabhupdesh** [comment]
Report name: Employee BasicHrDaDetails

**Comment by YashwanthGowdaJ** [comment]
The following changes were made as per Subash Sir,

1. Report request page is changed as per the request. Previously report can run only for 1 month at a time. Now based on From and To fields in request page, user can run for multiple months for the selected payroll.
2. Bonus amount is corrected.
3. Included new column by name CTCPayout .
4. Salary/Wages column is removed.
5. Pertol conveyance, Ayudha Pooja & other fields were updated with recent values.
6. Travel conveyance by company vehicle column is included for those employees whose in payelements Travel Conveyance pay element is not available.
7. For 2016-17 ( April, May & June) we have developed a new report(33010236) because those data is not available in 2016. So we have created new tables(Processed salary, Monthly attendance, Bonus Header & Bonus Line) imported data from 2009 database.
8. As data is not proper for 2017-18 year, we have hardcoded bonus year as 2016-2016 & 2017-2017.

**Comment by YashwanthGowdaJ** [comment]
Please neglect previous comment.

The following changes were made as per Subash Sir,

1. Previously there were 2 layout designs for workers and staff. Now we have combined both worker in same layout.
2. CTC calculation formula is changed, which includes some additional fields for CTC calculation.
3. The additional changes which we have done in summary report, same is updated in gross details report also.

**Comment by prabhupdesh** [comment]
[Report33010308.txt](https://github.com/BPS-Industries/Navision/files/4269970/Report33010308.txt)

**Comment by YashwanthGowdaJ** [comment]
[Rep employee gross 33010308 as on 290220.txt](https://github.com/BPS-Industries/Navision/files/4269992/Rep.employee.gross.33010308.as.on.290220.txt)

**Comment by YashwanthGowdaJ** [comment]
[Uploading Rep 33010308 .txt…]()

**Comment by YashwanthGowdaJ** [comment]
CTC calculation formula is changed as suggested by Subhash.
[Rep 33010308 .txt](https://github.com/BPS-Industries/Navision/files/4273772/Rep.33010308.txt)


CTC is the addition of Employer's Gross, Employer's PF, Employer's ESI , Medical Allowance, Petrol Convey, LWF per month, Attendance Allowance, Uniform Allowance, Travel Conveyance, Refreshment, Ayudha Pooja, Water charges, Bonus Provision, Gratuity & Severance.
