### ISSUE TITLE
Deferral  Functionality need to develop in Purchase invoice 

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#252]
Deferral Functionality

**Comment by Abigaiel** [comment]
@IT-Saravanan  @nagalakshmi2022 
I have created the deferral functionality and placed it in Purchase Invoice. It works when "Request  approval" button is used.
It works based on the Accrual Start and End date. It creates auto Entries based on these dates and gets posted in General Ledger Entries. The Deferral code gets created automatically when the "Request  Approval" is used.

**Comment by prabhupdesh** [comment]
1. Deferral Code in purchase line to be non editable
2. Accural start/end date cannot be changed after sending for approval i..e Status <> Open then dont allow any modification to these fields
3. Deferral schedule page to be made non editable
4. As discussed, deferral code generation to be at the time pf preview posting also. Deferral code once generated will remain as is and system to update no. of periods everytime this function is called.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
1. In purchase invoice I have made "Deferral code" field and "Deferral Schedule" page as non editable.
2. "Accrual start"/"End date" field is non editable after sending an approval.
3. Deferral functionality has been provided In "Preview posting" and "Request approval" buttons.
4. In Deferral functionality previously we used Straight line calculation method. As discussed now it has been changed into Days per period.

**Comment by Abigaiel** [comment]
The deferral code remains unchanged when Accrual dates are changed. Only the Number of Periods changes when these dates are changed.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In Purchase invoice we have added "Accrual Start date"/"End date" field  in purchase line. Deferral working based on purchase line data.  please check and confirm.

**Comment by shankar0517** [comment]
The Functionality which was previously created by Abigaiel has been put on hold and new functionality has been created for handling Pre-Paid Entries. These are following things which I have done based on discussion with Prabh sir for creating Deferral and handling Pre-Paid Entries.
1)New table has been created for Pre-Paid Entries.
2)New matrix page has been created for Pre-paid Entries.
3)In that new Matrix page have provided a button to import the data from purchase Invoice based on the Accrual Start and Accrual End Date.
4)Have Provided "Preview Posting" functionality so that if users use the button they can view the preview of the entries.
5)Have provided "Post" button. Deferral code gets created at the time of using this button. All the entries based on the Accrual dates and deferral code gets created in the General Ledger table.
All these are done in test server and these functionalities has been handed over to Sivam sir so that he can check and let us know in case of any discrepancies or errors.

**Comment by shankar0517** [comment]
The Functionality created by Abigaiel has been handed over to Sivam sir. This functionality will create Deferral code at the time of Sending Approval and when posted these entries gets auto populated in "Prepaid Entries" page and "General Ledger Entries" page based on the accrual Dates . Have asked Sivam Sir to check in Test server , so that he can use it and provide us more test cases.

**Comment by IT-Saravanan** [comment]
Completed.
