### ISSUE TITLE
Substitute Issue Allowed - Production Order Component

### ISSUE THREAD

**Issue by shankar0517** [BPS-Industries/Navision#280]
Need to place control in Production order component as stores people are using the "Select Item Substitution" button inappropriately.
Have to place controls for 'Leather' and 'Crust' Product Groups. Item substitution can be done for these two product groups only when the "Substitute Issue Allowed" field is marked. To Mark this field need to create a button in Production Order Components.

**Comment by shankar0517** [comment]
Have created this functionality in test server. After testing the functionality will move to live.

**Comment by YashwanthGowdaJ** [comment]
Moved to live.

Given a Boolean field in Prod. Order components page which can be enabled by only Rafik, using a button "Substitute Issue Allowed". And only he can able to select the relevant substitute Item for LE & CR. 

In consumption journal, "Select Substitute Item" button will not work for LE & CR.

**Comment by YashwanthGowdaJ** [comment]
For leather substitute items, we are updating production order component Line No. in consumption journal as 5, because of flowfield on issued Qty.
For leathers we have given seperate column in prod. order components page, called as "Substitute Item No.", this will get updated when Rafik selects the substitute item, and we are not updating the existing Item No. field.

Created a new option in consumption type called "Substitute" for substitute items
We are forcing users to 1st select the consumption type and then select all the remaining columns.

**Comment by IT-Saravanan** [comment]
Completed
